# Generated by Django 4.1.4 on 2022-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='src',
            field=models.CharField(max_length=300),
        ),
    ]
