# Generated by Django 4.1.4 on 2022-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_alter_incident_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
